services:
  bot:
    build: .
    container_name: magazin-bot
    restart: unless-stopped
    env_file:
      - .env
    volumes:
      - ./data:/app/prisma
    command: sh -c "npx prisma migrate deploy && node src/index.js"

  web:
    build: .
    container_name: magazin-web
    restart: unless-stopped
    env_file:
      - .env
    ports:
      - "3000:3000"
    volumes:
      - ./data:/app/prisma
    command: sh -c "npx prisma migrate deploy && node src/web/server.js"
    depends_on:
      - bot
